### PR TITLE
Hook up blob containing compliment

### PR DESCRIPTION
**Pull request by arichiardi**
This hooks up the completion (does not update the script for blob generation yet, I am working on the task still).

### CODE REVIEW

**Comment by pesterhazy** [comment]
Merged in master.

One difference I noticed is that even when returning plain names, compliment returns namespaces that haven't been required yet (e.g. clojure.data). That's pretty cool.

The main (potential) issue I see is how to deal with multiple unrepl connections. We don't want multiple versions of compliment to step on each other's toes. We could ...

- use ns munging
- check if the compliment ns exists before loading

We could add this behind a feature flag for now. That way it's "experimental" and opt-in until we fix the NS munging issue.

**Comment by arichiardi** [comment]
(repost from Slack) Yes compliment completion is way better, and this is still the very basic one. Cider does locals completion and adds ns + meta that can be displayed along with the candidates.

Ok I will rebase this on master , it will look better :smile:

I am not sold on munging on the client: it then needs to be aware of the content of the blob (and for instance `cmd-complete` needs to use the munged ns). It becomes stateful. Maybe this needs to be done on the server side?
Unrepl does the munging and for the client this is transparent, so the client always eval `compliment.core`.

If the plan is already to have it server side, then sorry for the noise here :smile:

**Comment by arichiardi** [comment]
Ok I rebased, tbh I don't think it is such a big feature that deserves an option at the moment...it is more like a test bed for understanding what to do with custom blobs and ns munging I think.

If I were to make this better I would pass `:context` and display completion with meta :smile:

**Comment by pesterhazy** [comment]
New PR for similar functionality: https://github.com/Unrepl/unravel/pull/36

**Pull request closed without merging**
