### PR TITLE
Homebrew formula

### PR DESCRIPTION
**Pull request by pesterhazy**

### CODE REVIEW

**Comment by pesterhazy** [comment]
How to make a homebrew tap: http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x

**Comment by bfontaine** [comment]
Hi @pesterhazy; too bad I just saw this PR because it would have been a pleasure to help you write a Homebrew formula for `unravel`, especially given that I already wrote one myself.

I submitted it to Homebrew’s core repository today so you might want to update your README to use [it](https://github.com/Homebrew/homebrew-core/blob/master/Formula/unravel.rb):

    brew install [--devel] unravel

It installs `unravel` 0.2.2 by default but switch to 0.3.0-beta.2 if you pass `--devel`. Also, it sets `UNRAVEL_HOME` so doesn’t require any modification in `unravel` itself.

**Comment by pesterhazy** [comment]
Hi @bfontaine, sorry for not getting back to you earlier.

It's great that you've added this to homebrew proper! I'm a bit worried about how this will interact with the version of lumo installed. My understanding is that you cannot choose which version of a dependency you want to install with homebrew. The latest unravel (0.3.0-beta.2) is only compatible with lumo 1.7.0+. I've seen reports of issues with this in the past.

The way I solved this (https://github.com/Unrepl/homebrew-bin/blob/master/unravel.rb) was to bundle a version of lumo, which admittedly is not very elegant. Does your formula ensure that the right version of lumo is picked?

**Comment by bfontaine** [comment]
The Homebrew formula for `unravel` depends on the Homebrew formula for `lumo`, which installs lumo 1.8.0 right now. There’s no hacky way to install a Homebrew formula with an older version of a dependency.

**Pull request merged**
