### PR TITLE
Add boot's socket-server usage

### PR DESCRIPTION
**Pull request by arichiardi**
:+1:

### CODE REVIEW

**Comment by pesterhazy** [comment]
@arichiardi thanks for the PR! Can you explain what the `(set-env!)` is for? Unravel ships its own unrepl blob so it shouldn't need any configuration on the server side.

**Comment by arichiardi** [comment]
@pesterhazy it is for setting up `boot` in `build.boot`, the alternative is `-d` to the boot command but I figured a lot of folks will use a `build.boot` with a `dev` task.

**Comment by pesterhazy** [comment]
@arichiardi yes, but I don't think it's needed. You don't need to add the unrepl dependency. `boot socket-server --port 50505 wait` should be sufficient (with or without a build.boot)

**Comment by arichiardi** [comment]
Oh ok...You know, I was sure I had tried without but I will try again and confirm it or delete this here.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arichiardi** [comment]
Ok first EuroClojure 2017 contribution from Berlin :smile:

**Comment by pesterhazy** [comment]
Thanks!

**Pull request merged**
